jenkins/job/execute:
	${CAULDRON_PATH}/modules/jenkins/scripts/jenkins.job.sh

jenkins/quietmode/set:
	${CAULDRON_PATH}/modules/jenkins/scripts/jenkins.quiet.set.sh

jenkins/wait:
	${CAULDRON_PATH}/modules/jenkins/scripts/jenkins.wait.sh
