CAULDRON_GIT_USER_EMAIL ?= "zebraproject@adyax.com"
CAULDRON_GIT_USER_NAME ?= "Zebra"

git/identity/set:
	git config --global user.email "$(CAULDRON_GIT_USER_EMAIL)"
	git config --global user.name "$(CAULDRON_GIT_USER_NAME)"

