CAULDRON_GIT_USER_EMAIL ?= "aroq.cauldron@github.com"
CAULDRON_GIT_USER_NAME ?= "Cauldron"

git/identity/set:
	git config --global user.email "$(CAULDRON_GIT_USER_EMAIL)"
	git config --global user.name "$(CAULDRON_GIT_USER_NAME)"

